-- MySQL Script generated by MySQL Workbench
-- Fri Oct  8 16:17:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `team27` ;

-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`Branch` ;

CREATE TABLE IF NOT EXISTS `team27`.`Branch` (
  `Id` INT NOT NULL,
  `Branch_name` VARCHAR(45) NOT NULL,
  `Opening_hours` DATETIME NOT NULL,
  `Phone` INT NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Suburb` VARCHAR(45) NOT NULL,
  `Postcode` INT NOT NULL,
  `List_of_unavailable_slots` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branch_unavailable_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`Branch_unavailable_time` ;

CREATE TABLE IF NOT EXISTS `team27`.`Branch_unavailable_time` (
  `Branch_datetime` DATETIME NOT NULL,
  `Branch_Id` INT NOT NULL,
  PRIMARY KEY (`Branch_datetime`),
  INDEX `fk_Branch_unavailable_time_Branch_idx` (`Branch_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_unavailable_time_Branch`
    FOREIGN KEY (`Branch_Id`)
    REFERENCES `mydb`.`Branch` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`GP` ;

CREATE TABLE IF NOT EXISTS `team27`.`GP` (
  `Id` INT NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Gname` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Available_slots` DATETIME NOT NULL,
  `Branch_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_GP_Branch1_idx` (`Branch_Id` ASC) VISIBLE,
  CONSTRAINT `fk_GP_Branch1`
    FOREIGN KEY (`Branch_Id`)
    REFERENCES `mydb`.`Branch` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`Patient` ;

CREATE TABLE IF NOT EXISTS `team27`.`Patient` (
  `Id` INT NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Gname` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `team27`.`Appointment` (
  `Id` INT NOT NULL,
  `Appointment_time` DATETIME NOT NULL,
  `Check_in` VARCHAR(45) NOT NULL,
  `GP_Id` INT NOT NULL,
  `Patient_Id` INT NOT NULL,
  `Branch_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Appointment_GP1_idx` (`GP_Id` ASC) VISIBLE,
  INDEX `fk_Appointment_Patient1_idx` (`Patient_Id` ASC) VISIBLE,
  INDEX `fk_Appointment_Branch1_idx` (`Branch_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_GP1`
    FOREIGN KEY (`GP_Id`)
    REFERENCES `mydb`.`GP` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`Patient_Id`)
    REFERENCES `mydb`.`Patient` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Branch1`
    FOREIGN KEY (`Branch_Id`)
    REFERENCES `mydb`.`Branch` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment_reason`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`Appointment_reason` ;

CREATE TABLE IF NOT EXISTS `team27`.`Appointment_reason` (
  `Id` INT NOT NULL,
  `Reason` VARCHAR(45) NOT NULL,
  `Appointment_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Appointment_reason_Appointment1_idx` (`Appointment_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_reason_Appointment1`
    FOREIGN KEY (`Appointment_Id`)
    REFERENCES `mydb`.`Appointment` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GP_timetable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team27`.`GP_timetable` ;

CREATE TABLE IF NOT EXISTS `team27`.`GP_timetable` (
  `Id` INT NOT NULL,
  `App_time` DATETIME NOT NULL,
  `GP_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_GP_timetable_GP1_idx` (`GP_Id` ASC) VISIBLE,
  CONSTRAINT `fk_GP_timetable_GP1`
    FOREIGN KEY (`GP_Id`)
    REFERENCES `mydb`.`GP` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
