INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('1', 'General inspection');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('2', 'Skin check');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('3', 'Breast check');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('4', 'Fever');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('5', 'Sore muscle');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('6', 'Bone damage');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('7', 'Open wounds');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('8', 'Headache');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('9', 'Cough');
INSERT INTO `team27`.`Appointment_reason` (`Id`, `Reason`) VALUES ('10', 'Covid vaccine');
